# Aggregation in Pandas

In [1]:
import pandas as pd

In [6]:
titanic = pd.read_csv('../../../data/titanic.csv')
titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,?,C,?,328,?
1305,3,0,"Zabour, Miss. Thamine",female,?,1,0,2665,14.4542,?,C,?,?,?
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.225,?,C,?,304,?
1307,3,0,"Zakarian, Mr. Ortin",male,27,0,0,2670,7.225,?,C,?,?,?
1308,3,0,"Zimmerman, Mr. Leo",male,29,0,0,315082,7.875,?,S,?,?,?

#### Convert the age column to a float

In [7]:
titanic['age'] = titanic['age'].replace(['?'], None).astype('float')

#### We will first create a group using the gender ('sex')

In [8]:
titanic_gender_group = titanic.groupby('sex')

## Now we will use .agg('function')

In [11]:
titanic_gender_group.agg('min')

,pclass,survived,name,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
sex,,,,,,,,,,,,,
female,1,0,"Abbott, Mrs. Stanton (Rosa Hunt)",0.1667,0,0,110152,10.4625,?,?,1,206,?
male,1,0,"Abbing, Mr. Anthony",0.3333,0,0,110413,0,?,C,1,1,?

In [12]:
titanic_gender_group.agg('max')

,pclass,survived,name,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
sex,,,,,,,,,,,,,
female,3,1,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",76.0,8,9,WE/P 5735,93.5,G6,S,D,?,"Zurich, Switzerland"
male,3,1,"van Melkebeke, Mr. Philemon",80.0,8,9,WE/P 5735,?,T,S,D,?,"Zurich, Switzerland"

## using .agg we can also pass a list of functions at once .agg(['function1', 'function2'])

In [16]:
titanic_gender_group['age'].agg(['min', 'max', 'mean', 'median'])

           min   max       mean  median
sex
female  0.1667  76.0  28.687071    27.0
male    0.3333  80.0  30.585233    28.0

## If we run a list of aggregated functions on an entire dataframe then things get chaotic

In [13]:
titanic_gender_group.agg(['min', 'max'])

       pclass     survived                                  name  \
          min max      min max                               min
sex
female      1   3        0   1  Abbott, Mrs. Stanton (Rosa Hunt)
male        1   3        0   1               Abbing, Mr. Anthony

                                                          age       sibsp      \
                                                  max     min   max   min max
sex
female  del Carlo, Mrs. Sebastiano (Argenia Genovesi)  0.1667  76.0     0   8
male                      van Melkebeke, Mr. Philemon  0.3333  80.0     0   8

        ... cabin     embarked     boat     body     home.dest  \
        ...   min max      min max  min max  min max       min
sex     ...
female  ...     ?  G6        ?   S    1   D  206   ?         ?
male    ...     ?   T        C   S    1   D    1   ?         ?


                        max
sex
female  Zurich, Switzerland
male    Zurich, Switzerland

[2 rows x 26 columns]

## So to prevent chaos we can perform column selection

In [18]:
titanic_gender_group[['age', 'pclass']].agg(['min', 'max', 'median'])

           age              pclass
           min   max median    min max median
sex
female  0.1667  76.0   27.0      1   3    2.0
male    0.3333  80.0   28.0      1   3    3.0

## We can go one level more deep by using separate functions for seperate columns in the grouped dataframe using a dictionary

In [20]:
titanic_gender_group.agg({'age': ['min', 'max'], 'pclass': ['median']})

           age       pclass
           min   max median
sex
female  0.1667  76.0    2.0
male    0.3333  80.0    3.0

# Now we will perform aggregation operations on the car_stocks.csv dataset

In [22]:
car_stocks = pd.read_csv('../../../data/car_stocks.csv')
car_stocks.head()

,Symbol,Date,Open,High,Low,Close,Adj Close,Volume
0,RIVN,2021-11-10,106.750000,119.459999,95.199997,100.730003,100.730003,103679500
1,RIVN,2021-11-11,114.625000,125.000000,108.010002,122.989998,122.989998,83668200
2,RIVN,2021-11-12,128.645004,135.199997,125.250000,129.949997,129.949997,50437500
3,RIVN,2021-11-15,130.800003,152.529999,127.510002,149.360001,149.360001,64982300
4,RIVN,2021-11-16,163.800003,179.470001,153.779999,172.009995,172.009995,94036600

In [23]:
car_stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Symbol     39 non-null     object
 1   Date       39 non-null     object
 2   Open       39 non-null     float64
 3   High       39 non-null     float64
 4   Low        39 non-null     float64
 5   Close      39 non-null     float64
 6   Adj Close  39 non-null     float64
 7   Volume     39 non-null     int64
dtypes: float64(5), int64(1), object(2)
memory usage: 2.6+ KB

In [24]:
symbol_group = car_stocks.groupby('Symbol')

In [28]:
symbol_group.agg({'Open' : 'mean', 'Close' : 'mean', 'Volume' : ['mean', 'sum']})

              Open       Close        Volume
              mean        mean          mean         sum
Symbol
GM       61.937693   62.164615  2.025259e+07   263283700
LCID     48.761538   49.829231  1.081098e+08  1405427200
RIVN    127.710000  127.523077  5.252395e+07   682811400