# Aggregations using Custom Functions

#### I want to find the difference between the highest and the lowest age by passenger class on the titanic

In [5]:
import pandas as pd

In [8]:
titanic = pd.read_csv('../../../data/titanic.csv')
titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,?,C,?,328,?
1305,3,0,"Zabour, Miss. Thamine",female,?,1,0,2665,14.4542,?,C,?,?,?
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.225,?,C,?,304,?
1307,3,0,"Zakarian, Mr. Ortin",male,27,0,0,2670,7.225,?,C,?,?,?
1308,3,0,"Zimmerman, Mr. Leo",male,29,0,0,315082,7.875,?,S,?,?,?

### Convert the age column to a float

In [12]:
titanic['age'] = titanic['age'].replace(['?'], None).astype('float')

### We will first create a group with passenger class on the titanic

In [13]:
titanic_class_group = titanic.groupby('pclass')

### We will create a function that gives the difference between the max and min of age

In [20]:
def age_diff(x):
    return x.max() - x.min()

In [23]:
titanic_class_group.agg({'age' : age_diff})

            age
pclass
1       79.0833
2       69.3333
3       73.8333

In [45]:
salaries = pd.read_csv('../../../data/Salaries.csv', low_memory=False)

# Now we will load another dataet and perform custom function agg

In [46]:
salaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

### We will create a function to find the number of NULL values in BasePay column
#### .count() function ignores the NULL Values of a series
#### .size actually counts everything including NULL values

In [47]:
salaries['BasePay'].count()

np.int64(148049)

In [48]:
salaries['BasePay'].size

148654

### We will create a function that can count NULLS

In [49]:
def null_counter(x):
    return x.size - x.count()

#### Now we will use our custom function 'null_counter' in a group by aggregation

In [56]:
salaries['Year'].unique()

array([2011, 2012, 2013, 2014])

In [65]:
salary_year_group = salaries.groupby('Year')

In [67]:
salary_year_group.agg({'BasePay' : null_counter})

      BasePay
Year
2011        0
2012        0
2013      605
2014        0