# Split / Apply / Combine

### Split the data into groups based on some criteria
### Apply function(s) to each group independently
### Combine the results into a new data structure

In [1]:
import pandas as pd

In [4]:
titanic = pd.read_csv('../../../data/titanic.csv')
titanic.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"

In [5]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1309 non-null   object
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1309 non-null   object
 9   cabin      1309 non-null   object
 10  embarked   1309 non-null   object
 11  boat       1309 non-null   object
 12  body       1309 non-null   object
 13  home.dest  1309 non-null   object
dtypes: int64(4), object(10)
memory usage: 143.3+ KB

In [7]:
titanic['age']

0           29
1       0.9167
2            2
3           30
4           25
         ...
1304      14.5
1305         ?
1306      26.5
1307        27
1308        29
Name: age, Length: 1309, dtype: object

In [10]:
titanic['age'] = titanic['age'].replace(['?'], None).astype('float')

In [15]:
titanic_group = titanic.groupby('sex')['age'].mean()
titanic_group

sex
female    28.687071
male      30.585233
Name: age, dtype: float64

In [13]:
titanic_group['age'].mean()

sex
female    28.687071
male      30.585233
Name: age, dtype: float64

In [16]:
titanic_pclass_group = titanic.groupby('pclass')

In [17]:
titanic_pclass_group['age'].mean()

pclass
1    39.159918
2    29.506705
3    24.816367
Name: age, dtype: float64

In [19]:
titanic_group_gender = titanic.groupby('sex')
titanic_group_gender

In [21]:
titanic_group_gender.mean(numeric_only=True)

          pclass  survived        age     sibsp     parch
sex
female  2.154506  0.727468  28.687071  0.652361  0.633047
male    2.372479  0.190985  30.585233  0.413998  0.247924