# Series
#### A series is a one-dimensional ndarray (n-dimensional array) with axis labels (basically a column with its label)

In [1]:
import pandas as pd 

titanic = pd.read_csv('../data/titanic.csv')

titanic.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"

In [4]:
# Example of a series (label + values)
# This is a one-dimensional array with labels
titanic.mean(numeric_only=True)

pclass      2.294882
survived    0.381971
sibsp       0.498854
parch       0.385027
dtype: float64

In [5]:
titanic.sum(numeric_only=True)

pclass      3004
survived     500
sibsp        653
parch        504
dtype: int64

In [11]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1309 non-null   object
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1309 non-null   object
 9   cabin      1309 non-null   object
 10  embarked   1309 non-null   object
 11  boat       1309 non-null   object
 12  body       1309 non-null   object
 13  home.dest  1309 non-null   object
dtypes: int64(4), object(10)
memory usage: 143.3+ KB

In [12]:
# Now we will try to perform SUM function on a particular column/Series
titanic['survived'].sum()

np.int64(500)

In [13]:
# Now we can find the min and max of a particular column as well
titanic['survived'].min()

np.int64(0)

In [14]:
titanic['survived'].max()

np.int64(1)

In [15]:
# We can also check the shapre of a series/column just like we do for a dataframe
titanic['sex'].shape

(1309,)

#### We can check the INDEX of a series

In [16]:
titanic['cabin'].index

RangeIndex(start=0, stop=1309, step=1)

In [17]:
mins = titanic.min(numeric_only=True)

In [18]:
mins.index

Index(['pclass', 'survived', 'sibsp', 'parch'], dtype='object')

In [19]:
mins

pclass      1
survived    0
sibsp       0
parch       0
dtype: int64

## Series Methods

In [21]:
# The head method on a series
titanic['cabin'].head(8)

0         B5
1    C22 C26
2    C22 C26
3    C22 C26
4    C22 C26
5        E12
6         D7
7        A36
Name: cabin, dtype: object

In [23]:
# We can also do a tail method on this as well
titanic['name'].tail(8)

1301         Youseff, Mr. Gerious
1302            Yousif, Mr. Wazli
1303        Yousseff, Mr. Gerious
1304         Zabour, Miss. Hileni
1305        Zabour, Miss. Thamine
1306    Zakarian, Mr. Mapriededer
1307          Zakarian, Mr. Ortin
1308           Zimmerman, Mr. Leo
Name: name, dtype: object

In [24]:
# We can do a describe on a series/column as well
titanic['survived'].describe()

count    1309.000000
mean        0.381971
std         0.486055
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000
Name: survived, dtype: float64

In [26]:
titanic['name'].describe()

count                     1309
unique                    1307
top       Connolly, Miss. Kate
freq                         2
Name: name, dtype: object

In [27]:
# We can do info() on a series/column as well
titanic['pclass'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1309 entries, 0 to 1308
Series name: pclass
Non-Null Count  Dtype
--------------  -----
1309 non-null   int64
dtypes: int64(1)
memory usage: 10.4 KB

In [30]:
# We can also do a DTYPES on a series
titanic['name'].dtype

dtype('O')

## UNIQUE() is a Series ONLY Method

In [32]:
titanic['home.dest'].unique()

array(['St Louis, MO', 'Montreal, PQ / Chesterville, ON', 'New York, NY',
       'Hudson, NY', 'Belfast, NI', 'Bayside, Queens, NY',
       'Montevideo, Uruguay', 'Paris, France', '?', 'Hessle, Yorks',
       'Montreal, PQ', 'Winnipeg, MN', 'San Francisco, CA',
       'Dowagiac, MI', 'Stockholm, Sweden / Washington, DC',
       'Trenton, NJ', 'Glen Ridge, NJ', 'Youngstown, OH',
       'Birkdale, England Cleveland, Ohio', 'London / Winnipeg, MB',
       'Cooperstown, NY', 'St Leonards-on-Sea, England Ohio',
       'Los Angeles, CA', 'Pomeroy, WA', 'Omaha, NE', 'Philadelphia, PA',
       'Denver, CO', 'Belmont, MA', 'Washington, DC',
       'Austria-Hungary / Germantown, Philadelphia, PA',
       'Germantown, Philadelphia, PA', 'Bryn Mawr, PA',
       'Ascot, Berkshire / Rochester, NY', 'Little Onn Hall, Staffs',
       'Amenia, ND', 'New York, NY / Ithaca, NY', 'London, England',
       'Liverpool, England / Belfast', 'Stoughton, MA', 'Victoria, BC',
       'Lakewood, NJ', 'Roachdale, IN', 'Milwaukee, WI', 'Lima, Peru',
       'Calgary, AB', 'Deephaven, MN / Cedar Rapids, IA',
       'London / Paris', 'Mt Airy, Philadelphia, PA', 'Brookline, MA',
       'Brooklyn, NY', 'Winnipeg, MB', 'Westcliff-on-Sea, Essex',
       'Zurich, Switzerland', 'Scituate, MA',
       "St Anne's-on-Sea, Lancashire", 'Paris, France / New York, NY',
       'Greenwich, CT', 'Kingston, Surrey', 'London / Middlesex',
       'Brighton, MA', 'London / Birmingham', 'Chicago, IL',
       'Indianapolis, IN', 'New York, NY /  Stamford CT',
       'Paris, France New York, NY', 'Liverpool', 'Bennington, VT',
       'London', 'Buffalo, NY', 'Southington / Noank, CT', 'Boston, MA',
       'Portland, OR', 'Stockholm, Sweden', 'Springfield, MA',
       'London / New York, NY', 'Brockton, MA', 'Belgium  Montreal, PQ',
       'Vancouver, BC', 'Dorchester, MA', 'East Bridgewater, MA',
       'Fond du Lac, WI', 'Green Bay, WI', 'Lexington, MA',
       'Isle of Wight, England', 'Providence, RI', '?Havana, Cuba',
       'Belfast', 'Surbiton Hill, Surrey', 'Isleworth, England',
       'Madrid, Spain', 'Toronto, ON', 'Worcester, MA',
       'Rotterdam, Netherlands', 'Paris /  New York, NY', 'Seattle, WA',
       'London  Vancouver, BC', 'Haverford, PA / Cooperstown, NY',
       'Manchester, England', 'New York, NY / Greenwich CT', 'Duluth, MN',
       'Basel, Switzerland', 'New Britain, CT',
       'St James, Long Island, NY', 'Huntington, WV', 'Streatham, Surrey',
       'Minneapolis, MN', 'Tuxedo Park, NY',
       'Wimbledon Park, London / Hayling Island, Hants', 'Newark, NJ',
       'Haverford, PA', 'Gallipolis, Ohio / ? Paris / New York',
       'Cincinatti, OH', 'Haddenfield, NJ', 'London /  East Orange, NJ',
       'Albany, NY', 'Mexico City, Mexico', 'East Orange, NJ',
       'England Salt Lake City, Utah', 'Brunswick, ME',
       'New York, NY / Briarcliff Manor NY', 'Elkins Park, PA',
       'Geneva, Switzerland / Radnor, PA', 'Halifax, NS',
       'New York, NY / Washington, DC', 'Russia New York, NY',
       'Bryn Mawr, PA, USA', 'Buenos Aires, Argentina / New Jersey, NJ',
       'Cornwall, England Houghton, MI', 'Warwick, England',
       'West Hoboken, NJ', 'Penzance, Cornwall / Akron, OH', 'Guernsey',
       'Bristol, Avon / Jacksonville, FL',
       'Plymouth, Dorset / Houghton, MI', 'Jacksonville, FL',
       'Norwich / New York, NY', 'England',
       'Guntur, India / Benton Harbour, MI', 'Rochester, NY',
       'St Ives, Cornwall / Calumet, MI', 'Elmira, NY / Orange, NJ',
       'Lake Arthur, Chavez County, NM', 'London / Montreal, PQ',
       'Cape Town, South Africa / Seattle, WA',
       'Skara, Sweden / Rockford, IL',
       'Sittingbourne, England / San Diego, CA', 'Southsea, Hants',
       'Bangkok, Thailand / Roseville, IL', 'Mamaroneck, NY', 'Bronx, NY',
       'Cornwall / Spokane, WA', 'England / San Francisco, CA',
       'Hartford, Huntingdonshire', 'Helsinki, Finland Ashtabula, Ohio',
       'London / Fort Byron, NY',
       'Bishopstoke, Hants / Fayette Valley, ID', 'Pennsylvania',
       'Provo, UT', 'Upper Burma, India Pittsburgh, PA',
       'St Ives, Cornwall / Hancock, MI', 'Lyndhurst, England',
       'London / Staten Island, NY', 'Portugal / Sau Paulo, Brazil',
       'Lucca, Italy / California', 'Guernsey / Elizabeth, NJ',
       'New Forest, England', 'Southampton', 'Holley, NY',
       'Greenport, NY', 'Barcelona, Spain / Havana, Cuba',
       'England / Detroit, MI', 'Goteborg, Sweden / Rockford, IL',
       'Oslo, Norway Bayonne, NJ', 'England / Philadelphia, PA',
       'Cornwall / Houghton, MI', 'Janjgir, India / Pennsylvania',
       'Liverpool / Montreal, PQ', 'Cornwall / Clear Creek, CO',
       'Cornwall', 'Cornwall / Camden, NJ', 'West Kensington, London',
       'Clevedon, England', 'Auburn, NY', 'Detroit, MI',
       'Seattle, WA / Toledo, OH', 'Denmark Hill, Surrey / Chicago',
       'Walthamstow, England', 'Ilford, Essex / Winnipeg, MB',
       'Somerset / Bernardsville, NJ', 'India / Rapid City, SD',
       'West Hampstead, London / Neepawa, MB',
       'Kontiolahti, Finland / Detroit, MI', 'Cornwall / Akron, OH',
       'Devonport, England', 'England / Sacramento, CA', 'Tokyo, Japan',
       'Swindon, England', 'North Evington, England',
       'St Ives, Cornwall / Houghton, MI', 'Moscow / Bronx, NY',
       'India / Pittsburgh, PA', 'Harrisburg, PA', 'Glasgow / Bangor, ME',
       'Sweden / Arlington, NJ', 'Paris / Haiti',
       'Berne, Switzerland / Central City, IA', 'London / Chicago, IL',
       'Weston-Super-Mare, Somerset', 'Southampton / New York, NY',
       'Paris', 'Paris / Montreal, PQ', 'St Austall, Cornwall',
       'Weston-Super-Mare / Moose Jaw, SK', 'Sydney, Australia',
       'Sarnia, ON', 'England / Bennington, VT', 'Chelsea, London',
       'Harrow-on-the-Hill, Middlesex', 'Copenhagen, Denmark',
       'Guernsey / Montclair, NJ and/or Toledo, Ohio', 'Frankfort, KY',
       'Halesworth, England', 'Cambridge, MA', 'Nice, France',
       'Cornwall / Hancock, MI', 'Glasgow', 'Cologne, Germany',
       'Folkstone, Kent / New York, NY', 'Middleburg Heights, OH',
       'Pondersend, England / New Durham, NJ', 'Spain / Havana, Cuba',
       'Hamilton, ON', 'St Andrews, Guernsey', 'Woodford County, KY',
       'Gunnislake, England / Butte, MT', 'Ilfracombe, Devon',
       'Worcester, England', 'Russia', 'Denmark / New York, NY',
       'Milford, NH', 'Plymouth, Devon / Detroit, MI', 'Brighton, Sussex',
       'Elizabeth, NJ', 'Spain',
       'London, England / Marietta, Ohio and Milwaukee, WI',
       'Guernsey / Wilmington, DE', 'Hornsey, England', 'Deer Lodge, MT',
       'Finland / Minneapolis, MN', 'Finland / Washington, DC',
       'Sault St Marie, ON', 'Catford, Kent / Detroit, MI',
       'Columbus, OH', 'Bath, England / Massachusetts',
       'Plymouth, England', 'Barre, Co Washington, VT',
       'Bristol, England / New Britain, CT', 'Aberdeen / Portland, OR',
       'England / Hartford, CT', 'Bromsgrove, England / Montreal, PQ',
       'Bournmouth, England', 'Guernsey, England / Edgewood, RI',
       'Harrow, England', 'Yoevil, England / Cottage Grove, OR',
       'East Providence, RI', 'Norway Los Angeles, CA',
       'Perkins County, SD', 'Taalintehdas, Finland Hoboken, NJ',
       'Greensburg, PA', 'Asarum, Sweden Brooklyn, NY',
       'Bournemouth, England', 'Sweden Akeley, MN',
       'London, England Norfolk, VA', 'Syria Fredericksburg, VA',
       'England Albion, NY', 'Salo, Finland Astoria, OR', 'Argentina',
       'Lower Clapton, Middlesex or Erdington, Birmingham',
       'Windsor, England New York, NY', 'Bergen, Norway',
       'Sweden Winnipeg, MN', 'Ruotsinphyhtaa, Finland New York, NY',
       'Vadsbro, Sweden Ministee, MI', 'Hartford, CT',
       'Sweden Chicago, IL', 'Bulgaria Chicago, IL',
       'Altdorf, Switzerland', 'Sweden Joliet, IL',
       'Sweden  Worcester, MA', 'Sweden Worcester, MA',
       'Oskarshamn, Sweden Minneapolis, MN', 'Ottawa, ON',
       'Krakoryd, Sweden Bloomington, IL', 'Syria Youngstown, OH',
       'Ruotsinphytaa, Finland New York, NY', 'Syria New York, NY',
       'London Skanteales, NY', 'Syria Ottawa, ON',
       'England New York, NY', 'Krakudden, Sweden Moune, IL',
       'Tranvik, Finland New York', 'Syria', 'Hong Kong New York, NY',
       'Brennes, Norway New York', 'Stockholm, Sweden New York',
       'Syria Kent, ON', 'Ireland Chicago, IL',
       'Treherbert, Cardiff, Wales',
       'Kingwilliamstown, Co Cork, Ireland Glens Falls, NY',
       'Medeltorp, Sweden Chicago, IL', 'Bridgerule, Devon',
       'Broomfield, Chelmsford, England', 'Co Cork, Ireland Roxbury, MA',
       'Kingwilliamstown, Co Cork, Ireland New York, NY',
       'Co Cork, Ireland Charlestown, MA',
       'Co Sligo, Ireland New York, NY', 'Croatia',
       'Ireland Philadelphia, PA', 'Dagsas, Sweden Fower, MN',
       'Goteborg, Sweden Huntley, IL',
       'Co Longford, Ireland New York, NY',
       'Co Sligo, Ireland Hartford, CT', 'St Denys, Southampton, Hants',
       'Ireland New York, NY', 'Greece', 'Portugal',
       'London Brooklyn, NY', 'Co Limerick, Ireland Sherbrooke, PQ',
       'Ireland Brooklyn, NY', 'Ireland', 'Austria',
       'England Brooklyn, NY', 'Merrill, WI',
       'Bristol, England Cleveland, OH',
       'Bournemouth, England Newark, NJ', 'Austria-Hungary',
       'Australia Fingal, ND', 'Norrlot, Sweden Chicago, IL',
       'Co Athlone, Ireland New York, NY', 'Stanton, IA',
       'West Bromwich, England Pontiac, MI',
       'Liverpool, England Bedford, OH', 'Tampico, MT',
       'Belgium Detroit, MI', 'Devon, England Wichita, KS',
       'Bulgaria Coon Rapids, IA',
       'Kilmacowen, Co Sligo, Ireland New York, NY',
       'England Oglesby, IL', 'Union Hill, NJ', 'London New York, NY',
       'Austria Niagara Falls, NY', 'West Haven, CT',
       'Tofta, Sweden Joliet, IL', 'Karberg, Sweden Jerome Junction, AZ',
       'Effington Rut, SD', 'Illinois, USA',
       'Aughnacliff, Co Longford, Ireland New York, NY',
       'Italy Philadelphia, PA',
       'Rotherfield, Sussex, England Essex Co, MA',
       'Bridgwater, Somerset, England',
       'Co Clare, Ireland Washington, DC',
       'Strood, Kent, England Detroit, MI',
       'Wiltshire, England Niagara Falls, NY', 'Dorking, Surrey, England',
       'Foresvik, Norway Portland, ND', 'Waukegan, Chicago, IL',
       'Myren, Sweden New York, NY', 'Finland Sudbury, ON',
       'Oslo, Norway Cameron, WI', 'Antwerp, Belgium / Stanton, OH'],
      dtype=object)

In [33]:
titanic['cabin'].unique()

array(['B5', 'C22 C26', 'E12', 'D7', 'A36', 'C101', '?', 'C62 C64', 'B35',
       'A23', 'B58 B60', 'D15', 'C6', 'D35', 'C148', 'C97', 'B49', 'C99',
       'C52', 'T', 'A31', 'C7', 'C103', 'D22', 'E33', 'A21', 'B10', 'B4',
       'E40', 'B38', 'E24', 'B51 B53 B55', 'B96 B98', 'C46', 'E31', 'E8',
       'B61', 'B77', 'A9', 'C89', 'A14', 'E58', 'E49', 'E52', 'E45',
       'B22', 'B26', 'C85', 'E17', 'B71', 'B20', 'A34', 'C86', 'A16',
       'A20', 'A18', 'C54', 'C45', 'D20', 'A29', 'C95', 'E25', 'C111',
       'C23 C25 C27', 'E36', 'D34', 'D40', 'B39', 'B41', 'B102', 'C123',
       'E63', 'C130', 'B86', 'C92', 'A5', 'C51', 'B42', 'C91', 'C125',
       'D10 D12', 'B82 B84', 'E50', 'D33', 'C83', 'B94', 'D49', 'D45',
       'B69', 'B11', 'E46', 'C39', 'B18', 'D11', 'C93', 'B28', 'C49',
       'B52 B54 B56', 'E60', 'C132', 'B37', 'D21', 'D19', 'C124', 'D17',
       'B101', 'D28', 'D6', 'D9', 'B80', 'C106', 'B79', 'C47', 'D30',
       'C90', 'E38', 'C78', 'C30', 'C118', 'D36', 'D48', 'D47', 'C105',
       'B36', 'B30', 'D43', 'B24', 'C2', 'C65', 'B73', 'C104', 'C110',
       'C50', 'B3', 'A24', 'A32', 'A11', 'A10', 'B57 B59 B63 B66', 'C28',
       'E44', 'A26', 'A6', 'A7', 'C31', 'A19', 'B45', 'E34', 'B78', 'B50',
       'C87', 'C116', 'C55 C57', 'D50', 'E68', 'E67', 'C126', 'C68',
       'C70', 'C53', 'B19', 'D46', 'D37', 'D26', 'C32', 'C80', 'C82',
       'C128', 'E39 E41', 'D', 'F4', 'D56', 'F33', 'E101', 'E77', 'F2',
       'D38', 'F', 'F G63', 'F E57', 'F E46', 'F G73', 'E121', 'F E69',
       'E10', 'G6', 'F38'], dtype=object)

In [34]:
titanic['sex'].unique()

array(['female', 'male'], dtype=object)

## NUNIQUE() method tells you the count of the unique values

In [35]:
titanic['home.dest'].nunique()

370

In [36]:
titanic['cabin'].nunique()

187

## DROPNA parameter
##### By default in a nunique() count the NAN are left out but using (dropna = False) we can make NAN values count as well

In [39]:
import pandas as pd

netflix = pd.read_csv('../data/netflix_titles.csv', sep='|')
netflix.head()

,Unnamed: 0,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [41]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    8807 non-null   int64
 1   show_id       8807 non-null   object
 2   type          8807 non-null   object
 3   title         8807 non-null   object
 4   director      6173 non-null   object
 5   cast          7982 non-null   object
 6   country       7976 non-null   object
 7   date_added    8797 non-null   object
 8   release_year  8807 non-null   int64
 9   rating        8803 non-null   object
 10  duration      8804 non-null   object
 11  listed_in     8807 non-null   object
 12  description   8807 non-null   object
dtypes: int64(2), object(11)
memory usage: 894.6+ KB

In [42]:
# NUNIQUE without NAN values
netflix['director'].nunique()

4528

In [43]:
netflix['director'].nunique(dropna=False)

4529

## nlargest() & nsamllest() methods of Series
##### It gives the n (n by default is 5) number of largest or smallest values in a series

In [45]:
import pandas as pd

housing = pd.read_csv('../data/kc_house_data.csv')
housing.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [46]:
# In case we want to know the top 5 house prices
housing['price'].nlargest()

7252    7700000.0
3914    7062500.0
9254    6885000.0
4411    5570000.0
1448    5350000.0
Name: price, dtype: float64

In [47]:
# In case we want to know the top 10 house prices
housing['price'].nlargest(10)

7252    7700000.0
3914    7062500.0
9254    6885000.0
4411    5570000.0
1448    5350000.0
1315    5300000.0
1164    5110800.0
8092    4668000.0
2626    4500000.0
8638    4489000.0
Name: price, dtype: float64

In [48]:
# In case we want to know the 10 lowest house prices in the dataset
housing['price'].nsmallest(10)

1149     75000.0
15293    78000.0
465      80000.0
16198    81000.0
8274     82000.0
2141     82500.0
18468    83000.0
3767     84000.0
10253    85000.0
16714    85000.0
Name: price, dtype: float64

##### keep = 'all' mmethod helps to deal with duplicate values when seeing nlargest or nsmallest

In [49]:
titanic['pclass'].nlargest(5)

600    3
601    3
602    3
603    3
604    3
Name: pclass, dtype: int64

In [50]:
titanic['pclass'].nlargest(5, keep='all')

600     3
601     3
602     3
603     3
604     3
       ..
1304    3
1305    3
1306    3
1307    3
1308    3
Name: pclass, Length: 709, dtype: int64

## nlargest() & nsmallest() in a dataframe

In [52]:
# We are filtering the dataframe to show us the TOP 10 houses by PRICES
housing.nlargest(10, ['price'])

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
7252,6762700020,20141013T000000,7700000.0,6,8.00,12050,27600,2.5,0,3,...,13,8570,3480,1910,1987,98102,47.6298,-122.323,3940,8800
3914,9808700762,20140611T000000,7062500.0,5,4.50,10040,37325,2.0,1,2,...,11,7680,2360,1940,2001,98004,47.6500,-122.214,3930,25449
9254,9208900037,20140919T000000,6885000.0,6,7.75,9890,31374,2.0,0,4,...,13,8860,1030,2001,0,98039,47.6305,-122.240,4540,42730
4411,2470100110,20140804T000000,5570000.0,5,5.75,9200,35069,2.0,0,0,...,13,6200,3000,2001,0,98039,47.6289,-122.233,3560,24345
1448,8907500070,20150413T000000,5350000.0,5,5.00,8000,23985,2.0,0,4,...,12,6720,1280,2009,0,98004,47.6232,-122.220,4600,21750
1315,7558700030,20150413T000000,5300000.0,6,6.00,7390,24829,2.0,1,4,...,12,5000,2390,1991,0,98040,47.5631,-122.210,4320,24619
1164,1247600105,20141020T000000,5110800.0,5,5.25,8010,45517,2.0,1,4,...,12,5990,2020,1999,0,98033,47.6767,-122.211,3430,26788
8092,1924059029,20140617T000000,4668000.0,5,6.75,9640,13068,1.0,1,4,...,12,4820,4820,1983,2009,98040,47.5570,-122.210,3270,10454
2626,7738500731,20140815T000000,4500000.0,5,5.50,6640,40014,2.0,1,4,...,12,6350,290,2004,0,98155,47.7493,-122.280,3030,23408
8638,3835500195,20140618T000000,4489000.0,4,3.00,6430,27517,2.0,0,0,...,12,6430,0,2001,0,98004,47.6208,-122.219,3720,14592

In [54]:
#  Top 10 cheapest houses in the housing dataframe
housing.nsmallest(10, ['price'])

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1149,3421079032,20150217T000000,75000.0,1,0.00,670,43377,1.0,0,0,...,3,670,0,1966,0,98022,47.2638,-121.906,1160,42882
15293,40000362,20140506T000000,78000.0,2,1.00,780,16344,1.0,0,0,...,5,780,0,1942,0,98168,47.4739,-122.280,1700,10387
465,8658300340,20140523T000000,80000.0,1,0.75,430,5050,1.0,0,0,...,4,430,0,1912,0,98014,47.6499,-121.909,1200,7500
16198,3028200080,20150324T000000,81000.0,2,1.00,730,9975,1.0,0,0,...,5,730,0,1943,0,98168,47.4808,-122.315,860,9000
8274,3883800011,20141105T000000,82000.0,3,1.00,860,10426,1.0,0,0,...,6,860,0,1954,0,98146,47.4987,-122.341,1140,11250
2141,1623049041,20140508T000000,82500.0,2,1.00,520,22334,1.0,0,0,...,5,520,0,1951,0,98168,47.4799,-122.296,1572,10570
18468,7999600180,20140529T000000,83000.0,2,1.00,900,8580,1.0,0,0,...,5,900,0,1918,0,98168,47.4727,-122.270,2060,6533
3767,1523049188,20150430T000000,84000.0,2,1.00,700,20130,1.0,0,0,...,6,700,0,1949,0,98168,47.4752,-122.271,1490,18630
10253,2422049104,20140915T000000,85000.0,2,1.00,830,9000,1.0,0,0,...,6,830,0,1939,0,98032,47.3813,-122.243,1160,7680
16714,1322049150,20150305T000000,85000.0,2,1.00,910,9753,1.0,0,0,...,5,910,0,1947,0,98032,47.3897,-122.236,1160,7405

In [59]:
# Find which homes have the largest number of bedrooms
housing.nlargest(10, ['bedrooms'])

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
15870,2402100895,20140625T000000,640000.0,33,1.75,1620,6000,1.0,0,0,...,7,1040,580,1947,0,98103,47.6878,-122.331,1330,4700
8757,1773100755,20140821T000000,520000.0,11,3.00,3000,4960,2.0,0,0,...,7,2400,600,1918,1999,98106,47.5560,-122.363,1420,4960
13314,627300145,20140814T000000,1148000.0,10,5.25,4590,10920,1.0,0,2,...,9,2500,2090,2008,0,98004,47.5861,-122.113,2730,10400
15161,5566100170,20141029T000000,650000.0,10,2.00,3610,11914,2.0,0,0,...,7,3010,600,1958,0,98006,47.5705,-122.175,2040,11914
19254,8812401450,20141229T000000,660000.0,10,3.00,2920,3745,2.0,0,0,...,7,1860,1060,1913,0,98105,47.6635,-122.320,1810,3745
4096,1997200215,20140507T000000,599999.0,9,4.50,3830,6988,2.5,0,0,...,7,2450,1380,1938,0,98103,47.6927,-122.338,1460,6291
4235,2902200015,20150106T000000,700000.0,9,3.00,3680,4400,2.0,0,0,...,7,2830,850,1908,0,98102,47.6374,-122.324,1960,2450
6079,9822700190,20140808T000000,1280000.0,9,4.50,3650,5000,2.0,0,0,...,8,2530,1120,1915,2010,98105,47.6604,-122.289,2510,5000
8546,424049043,20140811T000000,450000.0,9,7.50,4050,6504,2.0,0,0,...,7,4050,0,1996,0,98144,47.5923,-122.301,1448,3866
16844,8823900290,20150317T000000,1400000.0,9,4.00,4620,5508,2.5,0,0,...,11,3870,750,1915,0,98105,47.6684,-122.309,2710,4320

##### Performing a Double Sort

In [60]:
# In this case first we are sorting based on Bedrooms and then we are sorting on based on bathrooms
housing.nlargest(10, ['bedrooms', 'bathrooms'])

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
15870,2402100895,20140625T000000,640000.0,33,1.75,1620,6000,1.0,0,0,...,7,1040,580,1947,0,98103,47.6878,-122.331,1330,4700
8757,1773100755,20140821T000000,520000.0,11,3.00,3000,4960,2.0,0,0,...,7,2400,600,1918,1999,98106,47.5560,-122.363,1420,4960
13314,627300145,20140814T000000,1148000.0,10,5.25,4590,10920,1.0,0,2,...,9,2500,2090,2008,0,98004,47.5861,-122.113,2730,10400
19254,8812401450,20141229T000000,660000.0,10,3.00,2920,3745,2.0,0,0,...,7,1860,1060,1913,0,98105,47.6635,-122.320,1810,3745
15161,5566100170,20141029T000000,650000.0,10,2.00,3610,11914,2.0,0,0,...,7,3010,600,1958,0,98006,47.5705,-122.175,2040,11914
8546,424049043,20140811T000000,450000.0,9,7.50,4050,6504,2.0,0,0,...,7,4050,0,1996,0,98144,47.5923,-122.301,1448,3866
4096,1997200215,20140507T000000,599999.0,9,4.50,3830,6988,2.5,0,0,...,7,2450,1380,1938,0,98103,47.6927,-122.338,1460,6291
6079,9822700190,20140808T000000,1280000.0,9,4.50,3650,5000,2.0,0,0,...,8,2530,1120,1915,2010,98105,47.6604,-122.289,2510,5000
16844,8823900290,20150317T000000,1400000.0,9,4.00,4620,5508,2.5,0,0,...,11,3870,750,1915,0,98105,47.6684,-122.309,2710,4320
4235,2902200015,20150106T000000,700000.0,9,3.00,3680,4400,2.0,0,0,...,7,2830,850,1908,0,98102,47.6374,-122.324,1960,2450

## Selecting Multiple Columns using NESTED LISTS

In [63]:
netflix[['title', 'rating']]

                      title rating
0      Dick Johnson Is Dead  PG-13
1             Blood & Water  TV-MA
2                 Ganglands  TV-MA
3     Jailbirds New Orleans  TV-MA
4              Kota Factory  TV-MA
...                     ...    ...
8802                 Zodiac      R
8803            Zombie Dumb  TV-Y7
8804             Zombieland      R
8805                   Zoom     PG
8806                 Zubaan  TV-14

[8807 rows x 2 columns]

In [65]:
netflix[['title', 'rating', 'director']].describe()

                       title rating       director
count                   8807   8803           6173
unique                  8807     17           4528
top     Dick Johnson Is Dead  TV-MA  Rajiv Chilaka
freq                       1   3207             19

In [66]:
cols = ['price', 'zipcode', 'sqft_lot']
housing[cols]

          price  zipcode  sqft_lot
0      221900.0    98178      5650
1      538000.0    98125      7242
2      180000.0    98028     10000
3      604000.0    98136      5000
4      510000.0    98074      8080
...         ...      ...       ...
21608  360000.0    98103      1131
21609  400000.0    98146      5813
21610  402101.0    98144      1350
21611  400000.0    98027      2388
21612  325000.0    98144      1076

[21613 rows x 3 columns]

## value_counts() - Gives the count for each value in a series

In [68]:
housing['bedrooms'].value_counts()

bedrooms
3     9824
4     6882
2     2760
5     1601
6      272
1      199
7       38
0       13
8       13
9        6
10       3
11       1
33       1
Name: count, dtype: int64

In [70]:
netflix['director'].value_counts().head(10)

director
Rajiv Chilaka             19
Raúl Campos, Jan Suter    18
Marcus Raboy              16
Suhas Kadav               16
Jay Karas                 14
Cathy Garcia-Molina       13
Martin Scorsese           12
Youssef Chahine           12
Jay Chapman               12
Steven Spielberg          11
Name: count, dtype: int64

In [72]:
netflix['director'].value_counts(ascending=True)

director
Kirsten Johnson                   1
Evgeny Afineevsky                 1
Kristina Goolsby, Ashley York     1
Phil Joanou                       1
Anthony Pierce                    1
                                 ..
Jay Karas                        14
Suhas Kadav                      16
Marcus Raboy                     16
Raúl Campos, Jan Suter           18
Rajiv Chilaka                    19
Name: count, Length: 4528, dtype: int64

In [73]:
housing['floors'].value_counts()

floors
1.0    10680
2.0     8241
1.5     1910
3.0      613
2.5      161
3.5        8
Name: count, dtype: int64

In [74]:
# I want to know how many combinations of bedroom and bathrooms occur
housing[['bedrooms', 'bathrooms']].value_counts()

bedrooms  bathrooms
4         2.50         2502
3         2.50         2357
          1.75         1870
          1.00         1780
2         1.00         1558
                       ...
7         1.00            1
          3.25            1
          5.50            1
          5.75            1
33        1.75            1
Name: count, Length: 144, dtype: int64

In [76]:
# I want to know how many combinations of bedroom and bathrooms occurtype
type(housing[['bedrooms', 'bathrooms']].value_counts())

pandas.core.series.Series