# Grouping by Index

In [4]:
import pandas as pd
import matplotlib.pyplot as plt

plt.style.use('ggplot')

In [5]:
state_pops = pd.read_csv('../../../data/state_pops.csv')

In [15]:
state_pops.set_index(['state', 'year'], inplace=True)

In [16]:
state_pops

             population
state year
AL    2012    4817528.0
      2010    4785570.0
      2011    4801627.0
      2009    4757938.0
      2013    4833722.0
...                 ...
USA   2013  316128839.0
      2009  306771529.0
      2010  309326295.0
      2011  311582564.0
      2012  313873685.0

[1272 rows x 1 columns]

### We are finding the total population by year

In [18]:
state_pops.groupby(level=1).sum()

       population
year
1990  499245628.0
1991  505961884.0
1992  513028462.0
1993  519837190.0
1994  526251652.0
1995  532556806.0
1996  538788582.0
1997  545293864.0
1998  551708232.0
1999  558080362.0
2000  568135427.0
2001  573756684.0
2002  579074087.0
2003  584041961.0
2004  589437474.0
2005  594854560.0
2006  600565038.0
2007  606245409.0
2008  611948798.0
2009  617283468.0
2010  622373798.0
2011  626851708.0
2012  631398915.0
2013  635872764.0

### We will find the state with the minimum population

In [20]:
state_pops.groupby(level=0).min().head()

       population
state
AK       553290.0
AL      4050055.0
AR      2356586.0
AZ      3684097.0
CA     29959515.0

In [21]:
state_pops.groupby(level=[1,0]).min()

            population
year state
1990 AK       553290.0
     AL      4050055.0
     AR      2356586.0
     AZ      3684097.0
     CA     29959515.0
...                ...
2013 VT       626630.0
     WA      6971406.0
     WI      5742713.0
     WV      1854304.0
     WY       582658.0

[1272 rows x 1 columns]