# Hierarchical Column Names

In [8]:
import pandas as pd

In [9]:
titanic = pd.read_csv('../../../data/titanic.csv')
titanic.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"

In [12]:
titanic.set_index(['pclass', 'sex'], inplace=True)

In [25]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1309 entries, (np.int64(1), 'female') to (np.int64(3), 'male')
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   survived   1309 non-null   int64
 1   name       1309 non-null   object
 2   age        1309 non-null   float64
 3   sibsp      1309 non-null   int64
 4   parch      1309 non-null   int64
 5   ticket     1309 non-null   object
 6   fare       1309 non-null   object
 7   cabin      1309 non-null   object
 8   embarked   1309 non-null   object
 9   boat       1309 non-null   object
 10  body       1309 non-null   object
 11  home.dest  1309 non-null   object
dtypes: float64(1), int64(3), object(8)
memory usage: 125.6+ KB

In [22]:
titanic['age'] = pd.to_numeric(titanic['age'], errors='coerce').fillna(0)

In [26]:
titanic['fare'] = pd.to_numeric(titanic['fare'], errors='coerce').fillna(0)

In [27]:
titanic.head()

               survived                                             name  \
pclass sex
1      female         1                    Allen, Miss. Elisabeth Walton
       male           1                   Allison, Master. Hudson Trevor
       female         0                     Allison, Miss. Helen Loraine
       male           0             Allison, Mr. Hudson Joshua Creighton
       female         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)

                   age  sibsp  parch  ticket      fare    cabin embarked boat  \
pclass sex
1      female  29.0000      0      0   24160  211.3375       B5        S    2
       male     0.9167      1      2  113781  151.5500  C22 C26        S   11
       female   2.0000      1      2  113781  151.5500  C22 C26        S    ?
       male    30.0000      1      2  113781  151.5500  C22 C26        S    ?
       female  25.0000      1      2  113781  151.5500  C22 C26        S    ?

              body                        home.dest
pclass sex
1      female    ?                     St Louis, MO
       male      ?  Montreal, PQ / Chesterville, ON
       female    ?  Montreal, PQ / Chesterville, ON
       male    135  Montreal, PQ / Chesterville, ON
       female    ?  Montreal, PQ / Chesterville, ON

In [28]:
titanic.groupby('sex').agg({
    'age' : ['min', 'max', 'mean'],
    'fare' : ['min', 'max', 'mean'],
    'survived' : ['mean']
})

        age                   fare                       survived
        min   max       mean   min       max       mean      mean
sex
female  0.0  76.0  23.885372  6.75  512.3292  46.198097  0.727468
male    0.0  80.0  23.873171  0.00  512.3292  26.123575  0.190985

In [30]:
titanic_df = titanic.groupby('sex').agg({
                    'age' : ['min', 'max', 'mean'],
                    'fare' : ['min', 'max', 'mean'],
                    'survived' : ['mean']
                })

In [31]:
titanic_df.index

Index(['female', 'male'], dtype='object', name='sex')

#### We have got NESTED HIERARCHICAL columns

In [32]:
titanic_df.columns

MultiIndex([(     'age',  'min'),
            (     'age',  'max'),
            (     'age', 'mean'),
            (    'fare',  'min'),
            (    'fare',  'max'),
            (    'fare', 'mean'),
            ('survived', 'mean')],
           )

## To access these NESTED COLUMNS we need to use Tuples

In [33]:
titanic_df['age', 'mean']

sex
female    23.885372
male      23.873171
Name: (age, mean), dtype: float64