# Multi Index - XS Method (Cross Section)
##### It is an easier way to get/access a portion of a dataframe that is multi-indexed

In [2]:
import pandas as pd

In [3]:
state_pops = pd.read_csv('../../../data/state_pops.csv')
state_pops.head()

  state  year  population
0    AL  2012   4817528.0
1    AL  2010   4785570.0
2    AL  2011   4801627.0
3    AL  2009   4757938.0
4    AL  2013   4833722.0

In [6]:
state_pops.set_index(['state', 'year'], inplace=True)

### We used state_pops.loc[:, 1992, :] in the previous notebook to access the contents of the second index column

## Now we will use XS method to access the content of the index column wheen there are more than one index column involved
### level= helps to define either the position of the index column or the name of the index column directly

In [17]:
state_pops.xs(1992, level='year').head()

       population
state
AL      4154014.0
AK       588736.0
AZ      3915740.0
AR      2415984.0
CA     30974659.0

In [18]:
state_pops.xs(2013, level=1).head()

       population
state
AL      4833722.0
AK       735132.0
AZ      6626624.0
AR      2959373.0
CA     38332521.0