# Mutli-Indexing with set_index

In [1]:
import pandas as pd

In [4]:
state_pops = pd.read_csv('../../../data/state_pops.csv')

In [5]:
state_pops.head()

  state  year  population
0    AL  2012   4817528.0
1    AL  2010   4785570.0
2    AL  2011   4801627.0
3    AL  2009   4757938.0
4    AL  2013   4833722.0

### If we check the index of the state_pops dataframe we will see that it is a RANGE INDEX

In [6]:
state_pops.index

RangeIndex(start=0, stop=1272, step=1)

### If we use either 'State' or 'Year' column as Index then it won't be Unique. But for Index column we want something Unique. So what we do is take combine the State and Year to make a Unique Index column

In [7]:
state_pops.set_index(['state', 'year'])

             population
state year
AL    2012    4817528.0
      2010    4785570.0
      2011    4801627.0
      2009    4757938.0
      2013    4833722.0
...                 ...
USA   2013  316128839.0
      2009  306771529.0
      2010  309326295.0
      2011  311582564.0
      2012  313873685.0

[1272 rows x 1 columns]

In [8]:
state_pops.set_index(['year', 'state'])

             population
year state
2012 AL       4817528.0
2010 AL       4785570.0
2011 AL       4801627.0
2009 AL       4757938.0
2013 AL       4833722.0
...                 ...
     USA    316128839.0
2009 USA    306771529.0
2010 USA    309326295.0
2011 USA    311582564.0
2012 USA    313873685.0

[1272 rows x 1 columns]

In [9]:
state_pops.set_index(['year', 'state', 'population'])

Empty DataFrame
Columns: []
Index: [(2012, AL, 4817528.0), (2010, AL, 4785570.0), (2011, AL, 4801627.0), (2009, AL, 4757938.0), (2013, AL, 4833722.0), (2007, AL, 4672840.0), (2008, AL, 4718206.0), (2005, AL, 4569805.0), (2006, AL, 4628981.0), (2004, AL, 4530729.0), (2003, AL, 4503491.0), (2001, AL, 4467634.0), (2002, AL, 4480089.0), (1999, AL, 4430141.0), (2000, AL, 4452173.0), (1998, AL, 4404701.0), (1997, AL, 4367935.0), (1996, AL, 4331103.0), (1995, AL, 4296800.0), (1994, AL, 4260229.0), (1993, AL, 4214202.0), (1992, AL, 4154014.0), (1991, AL, 4099156.0), (1990, AL, 4050055.0), (1990, AK, 553290.0), (1992, AK, 588736.0), (1994, AK, 603308.0), (1991, AK, 570193.0), (1993, AK, 599434.0), (1995, AK, 604412.0), (1996, AK, 608569.0), (1998, AK, 619933.0), (1997, AK, 612968.0), (1999, AK, 624779.0), (2000, AK, 627963.0), (2001, AK, 633714.0), (2002, AK, 642337.0), (2003, AK, 648414.0), (2004, AK, 659286.0), (2005, AK, 666946.0), (2006, AK, 675302.0), (2007, AK, 680300.0), (2008, AK, 687455.0), (2013, AK, 735132.0), (2009, AK, 698895.0), (2010, AK, 713868.0), (2011, AK, 723375.0), (2012, AK, 730307.0), (2012, AZ, 6551149.0), (2011, AZ, 6468796.0), (2010, AZ, 6408790.0), (2013, AZ, 6626624.0), (2009, AZ, 6343154.0), (2007, AZ, 6167681.0), (2008, AZ, 6280362.0), (2005, AZ, 5839077.0), (2006, AZ, 6029141.0), (2004, AZ, 5652404.0), (2003, AZ, 5510364.0), (2001, AZ, 5273477.0), (2002, AZ, 5396255.0), (1999, AZ, 5023823.0), (2000, AZ, 5160586.0), (1998, AZ, 4883342.0), (1997, AZ, 4736990.0), (1996, AZ, 4586940.0), (1995, AZ, 4432499.0), (1993, AZ, 4065440.0), (1994, AZ, 4245089.0), (1991, AZ, 3788576.0), (1992, AZ, 3915740.0), (1990, AZ, 3684097.0), (1990, AR, 2356586.0), (1991, AR, 2383144.0), (1992, AR, 2415984.0), (1994, AR, 2494019.0), (1993, AR, 2456303.0), (1995, AR, 2535399.0), (1996, AR, 2572109.0), (1997, AR, 2601091.0), (1998, AR, 2626289.0), (2000, AR, 2678588.0), (1999, AR, 2651860.0), (2002, AR, 2705927.0), (2001, AR, 2691571.0), (2004, AR, 2749686.0), (2003, AR, 2724816.0), (2006, AR, 2821761.0), (2005, AR, 2781097.0), (2008, AR, 2874554.0), (2007, AR, 2848650.0), (2009, AR, 2896843.0), (2013, AR, 2959373.0), (2011, AR, 2938506.0), (2010, AR, 2922280.0), (2012, AR, 2949828.0), (2012, CA, 37999878.0), (2011, CA, 37668681.0), (2010, CA, 37333601.0), (2013, CA, 38332521.0), ...]

[1272 rows x 0 columns]