# applymap() method
#### applymap method in pandas applies a function to every single individual element (cell) across an entire DataFrame.

In [8]:
import pandas as pd

In [9]:
titanic = pd.read_csv('../../../data/titanic.csv')

In [10]:
titanic['age'] = titanic['age'].replace(['?'], [None]).astype('float')

In [11]:
def get_age_group(age):
    if age < 2:
        return 'infant'
    elif age < 12:
        return 'child'
    elif age < 18:
        return 'teen'
    elif age < 50:
        return 'adult'
    else:
        return 'senior'

In [12]:
titanic['age_group'] = titanic['age'].apply(get_age_group)

In [13]:
titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,age_group
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO",adult
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON",infant
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",child
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON",adult
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,?,C,?,328,?,teen
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,?,C,?,?,?,senior
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.225,?,C,?,304,?,adult
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.225,?,C,?,?,?,adult
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.875,?,S,?,?,?,adult

In [16]:
(titanic[['name', 'sex', 'age_group']].applymap(str.upper))

/var/folders/js/d6m95rq92m76bb_bzchbyb1c0000gn/T/ipykernel_59429/3579076160.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  (titanic[['name', 'sex', 'age_group']].applymap(str.upper))

                                                 name     sex age_group
0                       ALLEN, MISS. ELISABETH WALTON  FEMALE     ADULT
1                      ALLISON, MASTER. HUDSON TREVOR    MALE    INFANT
2                        ALLISON, MISS. HELEN LORAINE  FEMALE     CHILD
3                ALLISON, MR. HUDSON JOSHUA CREIGHTON    MALE     ADULT
4     ALLISON, MRS. HUDSON J C (BESSIE WALDO DANIELS)  FEMALE     ADULT
...                                               ...     ...       ...
1304                             ZABOUR, MISS. HILENI  FEMALE      TEEN
1305                            ZABOUR, MISS. THAMINE  FEMALE    SENIOR
1306                        ZAKARIAN, MR. MAPRIEDEDER    MALE     ADULT
1307                              ZAKARIAN, MR. ORTIN    MALE     ADULT
1308                               ZIMMERMAN, MR. LEO    MALE     ADULT

[1309 rows x 3 columns]