# Concatenating Series By Index
### If we do axis=1 then we can align them horizontally instead of vertically

In [1]:
import pandas as pd

In [2]:
c1 = pd.Series(['red', 'orange', 'yellow'])
c2 = pd.Series(['green', 'blue', 'purple'])

In [4]:
pd.concat([c1,c2], axis=0)

0       red
1    orange
2    yellow
0     green
1      blue
2    purple
dtype: object

# Using axis=1 pandas does the pairing using the INDEX as the joining part

In [5]:
pd.concat([c1,c2], axis=1)

        0       1
0     red   green
1  orange    blue
2  yellow  purple

In [7]:
fruits = pd.Series(
    data=['banana', 'orange', 'mango'],
    index=['b', 'o', 'm']
)

animals = pd.Series(
    data=['badger', 'owl', 'mouse'],
    index=['b', 'o', 'm']
)

In [12]:
pd.concat([fruits, animals],axis=1)

        0       1
b  banana  badger
o  orange     owl
m   mango   mouse

## Using keys= we can rename the column

In [13]:
pd.concat([fruits, animals],axis=1, keys=['fruit', 'animals'])

    fruit animals
b  banana  badger
o  orange     owl
m   mango   mouse