# Inner vs Outer Joins

In [1]:
import pandas as pd

In [8]:
fruits = pd.Series(
    data=['banana', 'orange', 'mango', 'cherry'],
    index=['b', 'o', 'm', 'c']
)

animals = pd.Series(
    data=['badger', 'owl', 'mouse', 'lamb', 'cat'],
    index=['b', 'o', 'm', 'l', 'c']
)

## The default JOIN is OUTER

In [9]:
pd.concat([fruits, animals], axis = 1, keys=('fruits', 'animals'))

   fruits animals
b  banana  badger
o  orange     owl
m   mango   mouse
c  cherry     cat
l     NaN    lamb

## INNER JOIN

In [16]:
pd.concat([fruits, animals], axis=1, join='inner', keys=('fruits', 'animals'))

   fruits animals
b  banana  badger
o  orange     owl
m   mango   mouse
c  cherry     cat