# dropna() & isna() - Null Handling

In [7]:
import pandas as pd

sales = pd.read_csv('../../data/sales.csv')
games = pd.read_csv('../../data/game_stats.csv')

In [8]:
games

       name      league  points  assists  rebounds
0       bob         nba    22.0      5.0      10.0
1    jessie         NaN    10.0      NaN       2.0
2       stu  euroleague     NaN      NaN       NaN
3   jackson         aba     9.0      NaN       2.0
4  timothee         NaN     8.0      NaN       NaN
5     steph         nba    49.0      8.0      10.0
6       NaN         NaN     NaN      NaN       NaN

In [9]:
sales

   rating  shipping_zip  billing_zip
0     5.0           NaN      81220.0
1     4.5       94931.0      94931.0
2     NaN       92625.0      92625.0
3     4.5       10003.0      10003.0
4     4.0           NaN      92660.0
5     NaN           NaN          NaN
6     NaN       60007.0      60007.0

# isna()

### Using isna() to check the NaN values in the dataframe - produces a boolean dataframe

In [10]:
games.isna()

    name  league  points  assists  rebounds
0  False   False   False    False     False
1  False    True   False     True     False
2  False   False    True     True      True
3  False   False   False     True     False
4  False    True   False     True      True
5  False   False   False    False     False
6   True    True    True     True      True

##### We can also use isna() to check for NaN values in a specific column

In [11]:
games['league'].isna()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
Name: league, dtype: bool

In [12]:
games[games['league'].isna()]

       name league  points  assists  rebounds
1    jessie    NaN    10.0      NaN       2.0
4  timothee    NaN     8.0      NaN       NaN
6       NaN    NaN     NaN      NaN       NaN