# DataFrame Analysis Exercise

**Import the `bestsellers.csv` dataset and use it to answer the following questions:**

* Find the lowest User Rating in the DF
* Find the highest Price in the DF
* What is the average User Rating?
* What the average User Rating of the first 5 rows?
* What User Review score appeared the most?
* What is the total (sum) of all the values in the Reviews column?
* How many different authors are featured in the dataset?
* Which author wrote the most number of books on the list?  How many did they write?

In [2]:
import pandas as pd 

best = pd.read_csv('../data/bestsellers.csv')
best.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [5]:
best.min()

Name           10-Day Green Smoothie Cleanse
Author                      Abraham Verghese
User Rating                              3.3
Reviews                                   37
Price                                      0
Year                                    2009
Genre                                Fiction
dtype: object

In [6]:
best.max()

Name           You Are a Badass: How to Stop Doubting Your Gr...
Author                                              Zhi Gang Sha
User Rating                                                  4.9
Reviews                                                    87841
Price                                                        105
Year                                                        2019
Genre                                                Non Fiction
dtype: object

In [8]:
best.mean(numeric_only=True)

User Rating        4.618364
Reviews        11953.281818
Price             13.100000
Year            2014.000000
dtype: float64

In [10]:
best_5 = best.head()
best_5.mean(numeric_only=True)

User Rating        4.7
Reviews        13494.0
Price             12.6
Year            2016.2
dtype: float64

In [11]:
best.mode(numeric_only=True)

    User Rating  Reviews  Price  Year
0           4.8   8580.0    8.0  2009
1           NaN      NaN    NaN  2010
2           NaN      NaN    NaN  2011
3           NaN      NaN    NaN  2012
4           NaN      NaN    NaN  2013
5           NaN      NaN    NaN  2014
6           NaN      NaN    NaN  2015
7           NaN      NaN    NaN  2016
8           NaN      NaN    NaN  2017
9           NaN      NaN    NaN  2018
10          NaN      NaN    NaN  2019

In [12]:
best.sum(numeric_only=True)

User Rating       2540.1
Reviews        6574305.0
Price             7205.0
Year           1107700.0
dtype: float64

In [16]:
best.describe(include='object')

,Name,Author,Genre
count,550,550,550
unique,351,248,2
top,Publication Manual of the American Psychologic...,Jeff Kinney,Non Fiction
freq,10,12,310

In [17]:
best.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    object
 1   Author       550 non-null    object
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64
 4   Price        550 non-null    int64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB

In [ ]:
#