In [3]:
import pandas as pd

states = pd.read_csv('../data/nst-est2020.csv')
states.head()

,SUMLEV,REGION,DIVISION,STATE,NAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019,POPESTIMATE042020,POPESTIMATE2020
0,10,0,0,0,United States,308745538,308758105,309327143,311583481,313877662,316059947,318386329,320738994,323071755,325122128,326838199,328329953,329398742,329484123
1,20,1,0,0,Northeast Region,55317240,55318414,55380764,55608318,55782661,55912775,56021339,56052790,56063777,56083383,56084543,56002934,55924275,55849869
2,20,2,0,0,Midwest Region,66927001,66929737,66975328,67164092,67348275,67576524,67765576,67885682,68018175,68160342,68263019,68340091,68357895,68316744
3,20,3,0,0,South Region,114555744,114563042,114869421,116019483,117264196,118397213,119666248,121049223,122419547,123611036,124649156,125686544,126494232,126662754
4,20,4,0,0,West Region,71945553,71946912,72101630,72791588,73482530,74173435,74933166,75751299,76570256,77267367,77841481,78300384,78622340,78654756

In [2]:
states.tail()

,SUMLEV,REGION,DIVISION,STATE,NAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019,POPESTIMATE042020,POPESTIMATE2020
52,40,4,9,53,Washington,6724540,6724540,6743009,6827479,6898599,6966252,7057531,7167287,7299961,7427951,7526793,7614024,7678379,7693612
53,40,3,5,54,West Virginia,1852994,1853008,1854265,1856606,1857446,1854768,1850569,1843332,1832435,1818683,1805953,1795263,1788150,1784787
54,40,2,3,55,Wisconsin,5686986,5687285,5690538,5705840,5720825,5738012,5753199,5762927,5775170,5793147,5809319,5824581,5833464,5832655
55,40,4,8,56,Wyoming,563626,563775,564531,567491,576656,582620,583159,586389,585243,579994,579054,580116,582030,582328
56,40,X,X,72,Puerto Rico,3725789,3726157,3721525,3678732,3634488,3593077,3534874,3473232,3406672,3325284,3193344,3193553,3167851,3159343

In [5]:
states.tail(52).head(51).sum(numeric_only = True)

SUMLEV                    2040
STATE                     1477
CENSUS2010POP        308745538
ESTIMATESBASE2010    308758105
POPESTIMATE2010      309327143
POPESTIMATE2011      311583481
POPESTIMATE2012      313877662
POPESTIMATE2013      316059947
POPESTIMATE2014      318386329
POPESTIMATE2015      320738994
POPESTIMATE2016      323071755
POPESTIMATE2017      325122128
POPESTIMATE2018      326838199
POPESTIMATE2019      328329953
POPESTIMATE042020    329398742
POPESTIMATE2020      329484123
dtype: int64